#!/usr/bin/env python3
'''
  Generates common/chat-inline-templates.h from the manifest
  common/chat-inline-templates.h.in.

  The manifest lists model architectures that need a built-in ("inline") Jinja
  chat template because their GGUF files ship without an embedded chat_template.
  Each entry is a placeholder comment of the form:

      /* <arch-name>: <path/to/template.jinja> */

  where <arch-name> matches llm_arch_name() in src/llama-arch.cpp and the path
  is relative to the repository root.

  This script embeds each referenced template file verbatim as a C raw string
  literal and writes the filled-in header to the build directory, so that
  common/chat.cpp can look the template up at runtime.

  Syntax:
    ./scripts/gen-chat-inline-templates.py --manifest <in> --repo-root <dir> --output <out>
'''
from __future__ import annotations

import argparse
import re
from pathlib import Path

# Matches a placeholder comment: /* arch-name: path/to/template.jinja */
PLACEHOLDER_RE = re.compile(r"/\*\s*([A-Za-z0-9._\-]+)\s*:\s*(\S+?)\s*\*/")


def pick_delimiter(content: str) -> str:
    '''Pick a raw-string delimiter that does not collide with the content.'''
    base = "LLAMACPP_TMPL"
    delim = base
    i = 0
    while f"){delim}\"" in content:
        i += 1
        delim = f"{base}{i}"
    return delim


def render(entries: list[tuple[str, str, str]]) -> str:
    lines: list[str] = []
    lines.append("// AUTO-GENERATED by scripts/gen-chat-inline-templates.py - DO NOT EDIT.")
    lines.append("// Source manifest: common/chat-inline-templates.h.in")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cstddef>")
    lines.append("")
    lines.append("struct common_chat_inline_template_entry {")
    lines.append("    const char * arch;")
    lines.append("    const char * tmpl;")
    lines.append("};")
    lines.append("")
    lines.append("static const common_chat_inline_template_entry COMMON_CHAT_INLINE_TEMPLATES[] = {")
    if entries:
        for arch, rel, content in entries:
            delim = pick_delimiter(content)
            lines.append(f"    // {arch}: {rel}")
            lines.append(f'    {{ "{arch}", R"{delim}({content}){delim}" }},')
    else:
        # zero-length arrays are not valid C++; keep a single null sentinel
        lines.append("    { nullptr, nullptr },")
    lines.append("};")
    lines.append("")
    lines.append(f"static const size_t COMMON_CHAT_INLINE_TEMPLATES_COUNT = {len(entries)};")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate chat-inline-templates.h")
    ap.add_argument("--manifest", required=True, help="path to chat-inline-templates.h.in")
    ap.add_argument("--repo-root", required=True, help="repository root (template paths are relative to it)")
    ap.add_argument("--output", required=True, help="path of the header to generate")
    args = ap.parse_args()

    repo_root = Path(args.repo_root)
    manifest = Path(args.manifest).read_text(encoding="utf-8")

    entries: list[tuple[str, str, str]] = []
    for match in PLACEHOLDER_RE.finditer(manifest):
        arch, rel = match.group(1), match.group(2)
        # read the template verbatim (no newline translation) so the embedded
        # string is a byte-for-byte copy of the source .jinja file
        content = (repo_root / rel).read_text(encoding="utf-8", newline="")
        entries.append((arch, rel, content))

    text = render(entries)

    output = Path(args.output)
    # write only when the content changes to avoid spurious rebuilds
    if output.exists() and output.read_text(encoding="utf-8", newline="") == text:
        return
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8", newline="")


if __name__ == "__main__":
    main()
